// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Authenticates a user and returns access and refresh tokens",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "User credentials",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User successfully authenticated",
                        "schema": {
                            "$ref": "#/definitions/auth.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "Logs out a user and clears the refresh token cookie",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "User logout",
                "responses": {
                    "200": {
                        "description": "User successfully logged out",
                        "schema": {
                            "$ref": "#/definitions/auth.LogoutResponse"
                        }
                    }
                }
            }
        },
        "/auth/online": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves a list of user IDs who are currently online",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "List online users",
                "responses": {
                    "200": {
                        "description": "List of online user IDs",
                        "schema": {
                            "$ref": "#/definitions/auth.OnlineListResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Refreshes access token using refresh token stored in cookie",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Refresh access token",
                "responses": {
                    "200": {
                        "description": "Token successfully refreshed",
                        "schema": {
                            "$ref": "#/definitions/auth.RefreshResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid or missing refresh token",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Registers a new user with email and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "User credentials",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "User successfully registered",
                        "schema": {
                            "$ref": "#/definitions/auth.RegisterResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cargo": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves a list of all cargos in the system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cargo"
                ],
                "summary": "List all cargos",
                "responses": {
                    "200": {
                        "description": "List of cargos",
                        "schema": {
                            "$ref": "#/definitions/cargo.ListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/cargo.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new cargo with the provided details via form-data",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cargo"
                ],
                "summary": "Create a new cargo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Номер груза",
                        "name": "cargoNumber",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Дата (RFC3339), например 2025-04-30T08:00:00Z",
                        "name": "date",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Дата погрузки/разгрузки (2025-04-30T08:00:00Z)",
                        "name": "loadUnloadDate",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Водитель",
                        "name": "driver",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Информация о перевозке",
                        "name": "transportationInfo",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Сумма выплаты, например 12345.67",
                        "name": "payoutAmount",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Дата выплаты (RFC3339)",
                        "name": "payoutDate",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Статус оплаты",
                        "name": "paymentStatus",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Условия выплаты",
                        "name": "payoutTerms",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "ID машины (c8169351-f6d8-4058-af4a-8ead3363fd92)",
                        "name": "truckId",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Груз успешно создан",
                        "schema": {
                            "$ref": "#/definitions/cargo.CreateResponse"
                        }
                    },
                    "400": {
                        "description": "Ошибки валидации или неверный формат данных",
                        "schema": {
                            "$ref": "#/definitions/cargo.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/cargo.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cargo/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves a cargo by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cargo"
                ],
                "summary": "Get a cargo by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cargo ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Cargo found",
                        "schema": {
                            "$ref": "#/definitions/cargo.GetResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid ID",
                        "schema": {
                            "$ref": "#/definitions/cargo.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/cargo.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a cargo by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cargo"
                ],
                "summary": "Delete a cargo by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cargo ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Cargo deleted",
                        "schema": {
                            "$ref": "#/definitions/cargo.DeleteResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid ID",
                        "schema": {
                            "$ref": "#/definitions/cargo.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/cargo.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates a cargo by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cargo"
                ],
                "summary": "Update a cargo by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cargo ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Cargo object to be updated",
                        "name": "cargo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/cargo.CreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Cargo updated",
                        "schema": {
                            "$ref": "#/definitions/cargo.GetResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid ID",
                        "schema": {
                            "$ref": "#/definitions/cargo.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/cargo.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/invitation/invite": {
            "post": {
                "description": "Creates a new invitation with the provided details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "invitation"
                ],
                "summary": "Create a new invitation",
                "parameters": [
                    {
                        "description": "Invitation object to be created",
                        "name": "invitation",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/invitation.CreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Invitation successfully created",
                        "schema": {
                            "$ref": "#/definitions/invitation.CreateResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON format",
                        "schema": {
                            "$ref": "#/definitions/invitation.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/invitation.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves user profile information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "User profile",
                "responses": {
                    "200": {
                        "description": "User profile information",
                        "schema": {
                            "$ref": "#/definitions/auth.ProfileResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/truck": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves a list of all trucks in the system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "truck"
                ],
                "summary": "List all trucks",
                "responses": {
                    "201": {
                        "description": "List of trucks",
                        "schema": {
                            "$ref": "#/definitions/truck.ListResponse"
                        }
                    },
                    "404": {
                        "description": "Trucks not found",
                        "schema": {
                            "$ref": "#/definitions/truck.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new truck with the provided details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "truck"
                ],
                "summary": "Create a new truck",
                "parameters": [
                    {
                        "description": "Truck object to be created",
                        "name": "truck",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/truck.CreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Cargo successfully created",
                        "schema": {
                            "$ref": "#/definitions/cargo.CreateResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON format",
                        "schema": {
                            "$ref": "#/definitions/cargo.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/cargo.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/truck/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves a truck by their ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "truck"
                ],
                "summary": "Get a truck by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Truck ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Truck found",
                        "schema": {
                            "$ref": "#/definitions/truck.GetResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid ID",
                        "schema": {
                            "$ref": "#/definitions/truck.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Truck not found",
                        "schema": {
                            "$ref": "#/definitions/truck.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/truck/{id}/cargos": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves a list of cargos by their truck ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "truck"
                ],
                "summary": "Get a list of cargos by truck ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Truck ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Limit number of cargos per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number for pagination",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "List of cargos",
                        "schema": {
                            "$ref": "#/definitions/cargo.ListResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid ID",
                        "schema": {
                            "$ref": "#/definitions/cargo.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Truck not found",
                        "schema": {
                            "$ref": "#/definitions/cargo.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves a list of all users in the system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "List all users",
                "responses": {
                    "201": {
                        "description": "List of users",
                        "schema": {
                            "$ref": "#/definitions/user.ListResponse"
                        }
                    },
                    "404": {
                        "description": "Users not found",
                        "schema": {
                            "$ref": "#/definitions/user.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "description": "Retrieves a user by their ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get a user by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "User found",
                        "schema": {
                            "$ref": "#/definitions/user.GetResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid ID",
                        "schema": {
                            "$ref": "#/definitions/user.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/user.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a user by their ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Delete a user by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "User deleted",
                        "schema": {
                            "$ref": "#/definitions/user.DeleteResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid ID",
                        "schema": {
                            "$ref": "#/definitions/user.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/user.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/validate-token": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Validates an access token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Validate token",
                "responses": {
                    "200": {
                        "description": "Token is valid",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.ErrorResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string",
                    "example": "Некорректные данные"
                }
            }
        },
        "auth.LoginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "firulvv@mail.ru"
                },
                "password": {
                    "type": "string",
                    "example": "123456"
                }
            }
        },
        "auth.LoginResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "Пользователь успешно авторизован"
                }
            }
        },
        "auth.LogoutResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Успешный выход из системы"
                }
            }
        },
        "auth.OnlineListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "Список ID-шников онлайн пользователей"
                }
            }
        },
        "auth.ProfileResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/user.User"
                },
                "message": {
                    "type": "string",
                    "example": "Данные о пользователе"
                }
            }
        },
        "auth.RefreshResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "Токен успешно обновлён"
                }
            }
        },
        "auth.RegisterRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "firulvv@mail.ru"
                },
                "inviteToken": {
                    "type": "string",
                    "example": "token"
                },
                "password": {
                    "type": "string",
                    "example": "123456"
                }
            }
        },
        "auth.RegisterResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/user.User"
                },
                "message": {
                    "type": "string",
                    "example": "Пользователь успешно зарегистрирован"
                }
            }
        },
        "cargo.Cargo": {
            "type": "object",
            "required": [
                "cargoNumber",
                "driver",
                "transportationInfo",
                "truckId"
            ],
            "properties": {
                "cargoNumber": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "driver": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "loadUnloadDate": {
                    "type": "string"
                },
                "paymentStatus": {
                    "type": "string"
                },
                "payoutAmount": {
                    "type": "number"
                },
                "payoutDate": {
                    "type": "string"
                },
                "payoutTerms": {
                    "type": "string"
                },
                "transportationInfo": {
                    "type": "string"
                },
                "truckId": {
                    "type": "string"
                }
            }
        },
        "cargo.CreateRequest": {
            "type": "object",
            "required": [
                "cargoNumber",
                "driver",
                "transportationInfo",
                "truckId"
            ],
            "properties": {
                "cargoNumber": {
                    "type": "string",
                    "example": "1234"
                },
                "date": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                },
                "driver": {
                    "type": "string",
                    "example": "Иванов Иван Иванович"
                },
                "loadUnloadDate": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                },
                "paymentStatus": {
                    "type": "string",
                    "example": "paid"
                },
                "payoutAmount": {
                    "type": "number",
                    "example": 1000
                },
                "payoutDate": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                },
                "payoutTerms": {
                    "type": "string",
                    "example": "cash"
                },
                "transportationInfo": {
                    "type": "string",
                    "example": "Грузоперевозка"
                },
                "truckId": {
                    "type": "string",
                    "example": "1"
                }
            }
        },
        "cargo.CreateResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/cargo.Cargo"
                },
                "message": {
                    "type": "string",
                    "example": "Груз успешно создан"
                }
            }
        },
        "cargo.DeleteResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string",
                    "example": "Груз успешно удалён"
                }
            }
        },
        "cargo.ErrorResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string",
                    "example": "Невалидный формат JSON"
                }
            }
        },
        "cargo.GetResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/cargo.Cargo"
                },
                "message": {
                    "type": "string",
                    "example": "Данные о грузе"
                }
            }
        },
        "cargo.ListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/cargo.Cargo"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "Список всех грузов"
                }
            }
        },
        "invitation.CreateRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "firulvv@mail.ru"
                }
            }
        },
        "invitation.CreateResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string"
                },
                "message": {
                    "type": "string",
                    "example": "Приглашение успешно создано"
                }
            }
        },
        "invitation.ErrorResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string",
                    "example": "Невалидный формат JSON"
                }
            }
        },
        "truck.CreateRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "Машина"
                }
            }
        },
        "truck.ErrorResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string",
                    "example": "Невалидный формат JSON"
                }
            }
        },
        "truck.GetResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/truck.Truck"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "Машина"
                }
            }
        },
        "truck.ListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/truck.Truck"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "Список всех машин"
                }
            }
        },
        "truck.Truck": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "user.DeleteResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string",
                    "example": "Пользователь успешно удалён"
                }
            }
        },
        "user.ErrorResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string",
                    "example": "Невалидный формат JSON"
                }
            }
        },
        "user.GetResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/user.User"
                },
                "message": {
                    "type": "string",
                    "example": "Пользователь"
                }
            }
        },
        "user.ListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/user.User"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "Список пользователей"
                }
            }
        },
        "user.Role": {
            "type": "string",
            "enum": [
                "USER",
                "EDITOR",
                "SUPERADMIN"
            ],
            "x-enum-varnames": [
                "RoleUser",
                "RoleEditor",
                "RoleSuperAdmin"
            ]
        },
        "user.User": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "role": {
                    "$ref": "#/definitions/user.Role"
                },
                "username": {
                    "type": "string",
                    "minLength": 3
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Bearer token for authenticated requests",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Cargo Project API",
	Description:      "This is the API for the Cargo Project",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
